# Mengimport Library

In [25]:
import tensorflow as tf # untuk operasi tensor
import numpy as np # untuk operasi aritmatika

# Membuat tensor bernilai random dengan shape 5 x 5

In [4]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1) # buat tensor random dan dimasukkan ke variable
random_tensor.numpy() # tampilkan dalam bentuk numpy

array([[-0.28433853,  0.8922832 ,  0.8983451 ,  0.7163981 ,  0.34969485],
       [-0.37960768,  0.01531979,  0.27423722, -2.214901  , -0.08514621],
       [ 1.0113182 ,  0.6616626 ,  1.383323  , -0.40465203,  0.86142987],
       [-0.12589967, -1.418615  ,  2.0295074 ,  0.15304402,  0.13658497],
       [-0.49787143,  0.38847125, -0.4244715 ,  0.46214256, -0.5444318 ]],
      dtype=float32)

# Buat tensor bernilai bilangan prima dengan shape 5 x 5

In [6]:
list_prime = [[2,3,5,7,11],[13,17,19,23,29],[31,37,41,43,47],[53,59,61,71,73],[79,83,89,97,1]] # buat list 5x5 bernilai bilangan prima

prime_tensor = tf.constant(list_prime, dtype=tf.float32) # buat tensor dari list bilangan prima yang telah dibuat dan dimasukkan ke variable
prime_tensor.numpy() # tampilkan dalam bentuk numpy

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

# Menampilkan dimensi kedua variable tsb

In [7]:
random_tensor.shape # menampilkan dimensi random_tensor

TensorShape([5, 5])

In [26]:
prime_tensor.shape # menampilkan dimensi prime_tensor

TensorShape([5, 5])

# Menampilkan hasil perhitungan aritmatika 2 var tsb

In [10]:
print("prime_tensor + random_tensor :\n", tf.add(prime_tensor,random_tensor)) # tf.add untuk penambahan 

prime_tensor + random_tensor :
 tf.Tensor(
[[ 1.7156615  3.8922832  5.898345   7.7163982 11.349695 ]
 [12.620392  17.01532   19.274237  20.785099  28.914854 ]
 [32.01132   37.661663  42.383324  42.59535   47.86143  ]
 [52.8741    57.581387  63.029507  71.153046  73.13658  ]
 [78.50213   83.38847   88.57553   97.46214    0.4555682]], shape=(5, 5), dtype=float32)


In [12]:
print("prime_tensor - random_tensor :\n", tf.subtract(prime_tensor,random_tensor)) # tf.subtract untuk pengurangan  

prime_tensor - random_tensor :
 tf.Tensor(
[[ 2.2843385  2.1077168  4.101655   6.2836018 10.650305 ]
 [13.379608  16.98468   18.725763  25.214901  29.085146 ]
 [29.988682  36.338337  39.616676  43.40465   46.13857  ]
 [53.1259    60.418613  58.970493  70.846954  72.86342  ]
 [79.49787   82.61153   89.42447   96.53786    1.5444318]], shape=(5, 5), dtype=float32)


In [13]:
print("prime_tensor * random_tensor :\n", tf.multiply(prime_tensor,random_tensor)) # tf.multiply untuk perkalian 

prime_tensor * random_tensor :
 tf.Tensor(
[[ -0.56867707   2.6768496    4.4917254    5.0147867    3.8466434 ]
 [ -4.9349       0.2604365    5.210507   -50.942722    -2.4692402 ]
 [ 31.350864    24.481516    56.71624    -17.400038    40.487206  ]
 [ -6.672683   -83.69828    123.79995     10.866125     9.970702  ]
 [-39.331844    32.243114   -37.77796     44.827827    -0.5444318 ]], shape=(5, 5), dtype=float32)


In [14]:
print("prime_tensor / random_tensor :\n", tf.divide(prime_tensor,random_tensor)) # tf.divide untuk pembagian 

prime_tensor / random_tensor :
 tf.Tensor(
[[  -7.033869     3.3621612    5.5657897    9.771103    31.455997 ]
 [ -34.245884  1109.6754      69.28308    -10.384212  -340.5906   ]
 [  30.653063    55.919743    29.638777  -106.26414     54.560448 ]
 [-420.97012    -41.589863    30.056555   463.91882    534.4658   ]
 [-158.6755     213.65802   -209.6725     209.89194     -1.8367773]], shape=(5, 5), dtype=float32)


In [27]:
print("prime_tensor ^ random_tensor :\n", tf.pow(prime_tensor,random_tensor)) # tf.pow untuk perpangkatan 

prime_tensor ^ random_tensor :
 tf.Tensor(
[[8.2111800e-01 2.6651845e+00 4.2453771e+00 4.0311284e+00 2.3129683e+00]
 [3.7769267e-01 1.0443600e+00 2.2422385e+00 9.6362422e-04 7.5072753e-01]
 [3.2228584e+01 1.0904867e+01 1.7021622e+02 2.1827987e-01 2.7567350e+01]
 [6.0661650e-01 3.0749836e-03 4.2008784e+03 1.9201007e+00 1.7968090e+00]
 [1.1356008e-01 5.5655317e+00 1.4877827e-01 8.2826967e+00 1.0000000e+00]], shape=(5, 5), dtype=float32)


# Menampilkan nilai maksimal dan minimal random_tensor

In [16]:
tf.argmax(random_tensor, axis=0).numpy() # untuk menampilkan nilai maksimal dari tiap baris random_tensor karena axis nya 0

array([2, 2, 2, 2, 3], dtype=int64)

In [18]:
tf.argmin(random_tensor, axis=0).numpy() # untuk menampilkan nilai minimum dari tiap baris random_tensor karena axis nya 0

array([4, 3, 4, 1, 4], dtype=int64)

# Menampilkan hasil penggabungan variable random_tensor dengan prime_tensor

In [28]:
tf.concat([random_tensor,prime_tensor], axis=1) # tf.concat untuk menggabungkan tensor, dan axis 0 artinya yang digabung adalah per baris

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-2.8433853e-01,  8.9228320e-01,  8.9834511e-01,  7.1639812e-01,
         3.4969485e-01,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [-3.7960768e-01,  1.5319794e-02,  2.7423722e-01, -2.2149010e+00,
        -8.5146211e-02,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 1.0113182e+00,  6.6166258e-01,  1.3833230e+00, -4.0465203e-01,
         8.6142987e-01,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-1.2589967e-01, -1.4186150e+00,  2.0295074e+00,  1.5304402e-01,
         1.3658497e-01,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-4.9787143e-01,  3.8847125e-01, -4.2447150e-01,  4.6214256e-01,
        -5.4443181e-01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0000000e+00]], dtype=float32)>

# Menampilkan hasil sorting dari kedua variable tsb secara descending

In [21]:
sorted_random1 = tf.sort(random_tensor, direction="DESCENDING") # tf.sort untuk mensorting, dan direction nya untuk menentukan arah sortingan nya ascending atau descending
sorted_random1.numpy() # menampilkan dalam bentuk numpy

array([[ 0.8983451 ,  0.8922832 ,  0.7163981 ,  0.34969485, -0.28433853],
       [ 0.27423722,  0.01531979, -0.08514621, -0.37960768, -2.214901  ],
       [ 1.383323  ,  1.0113182 ,  0.86142987,  0.6616626 , -0.40465203],
       [ 2.0295074 ,  0.15304402,  0.13658497, -0.12589967, -1.418615  ],
       [ 0.46214256,  0.38847125, -0.4244715 , -0.49787143, -0.5444318 ]],
      dtype=float32)

In [22]:
sorted_prime1 = tf.sort(prime_tensor, direction="DESCENDING") # tf.sort untuk mensorting, dan direction nya untuk menentukan arah sortingan nya ascending atau descending
sorted_prime1.numpy() # menampilkan dalam bentuk numpy

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)

In [23]:
sorted_random2 = tf.argsort(random_tensor, direction="DESCENDING") # tf.argsort untuk mensorting dan nilai yang dikembalikan adalah indeks nya, dan direction nya untuk menentukan arah sortingan nya ascending atau descending
sorted_random2.numpy() # menampilkan dalam bentuk numpy

array([[2, 1, 3, 4, 0],
       [2, 1, 4, 0, 3],
       [2, 0, 4, 1, 3],
       [2, 3, 4, 0, 1],
       [3, 1, 2, 0, 4]])

In [24]:
sorted_prime2 = tf.argsort(prime_tensor, direction="DESCENDING")  # tf.argsort untuk mensorting dan nilai yang dikembalikan adalah indeks nya, dan direction nya untuk menentukan arah sortingan nya ascending atau descending
sorted_prime2.numpy() # menampilkan dalam bentuk numpy

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])